### ISSUE TITLE
Fix dialog width in "Dialog -> Positioning" section

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#12]
Fix the dialog width in the demo to fit the inputs width (make it smaller).

https://dwcj.org/docs/components/dialog#positioning

**Comment by bbrennanbasis** [comment]
This issue only concerns files in the webforj-docs-samples archive. Because of this, I'll close this bug and use  https://github.com/webforj/webforj-docs-samples/issues/55 to track it.
