### ISSUE TITLE
The docs does not support  DWC themes. 

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#17]
Currently the docs does not support viewing the samples in dark mode. Figure out a way to include an option in the docs navbar to switch all demos theme from light to dark.

**Comment by mhawkinsbasis** [comment]
Spoke about perhaps doing this with the Theme annotation using the system theme

**Comment by MatthewHawkins** [comment]
Fixed with the introduction of theme querying from Hyyan - demos should now respect this via a query param that the ComponentDemo component sets based on the current docusaurus theme
