### ISSUE TITLE
Remove the usage of `<html>` tag from the docs and samples

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#177]
https://github.com/webforj/webforj/pull/638

Remove the usage of the `<html>` tag from the documentation and samples, and switch to using the `setHtml` method. Don't Mention the `<html>` tag.

For instance : 
https://documentation.webforj.com/docs/components/button#adding-icons-to-buttons

**Comment by bbrennanbasis** [comment]
The usage of the `<html>` tag in the docs was only in reference to adding an icon. The following PRs combined will resolve this issue for the docs:

- PR #286 
- PR #283

The usage of the `<html>` tag in the samples will be addressed in the webforj-docs-samples [PR #89](https://github.com/webforj/webforj-docs-samples/pull/89).

**Comment by bbrennanbasis** [comment]
> The usage of the `<html>` tag in the docs was only in reference to adding an icon. The following PRs combined will resolve this issue for the docs:
> 
> * PR [PR: Updated "Adding icons to buttons" section #286](https://github.com/webforj/webforj-docs/pull/286)
> * PR [PR: Icon Component Article #283](https://github.com/webforj/webforj-docs/pull/283)
> 
> The usage of the `<html>` tag in the samples will be addressed in the webforj-docs-samples [PR #89](https://github.com/webforj/webforj-docs-samples/pull/89).

All the PRs mentioned in this previous comment have been merged, so this issue is now closed.
