### ISSUE TITLE
Document slider component

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#181]
https://github.com/webforj/webforj/pull/651

**Comment by gosteenBASIS** [comment]
The Slider component is documented here:
https://documentation.webforj.com/docs/components/slider
https://github.com/webforj/webforj-docs/blame/website/docs/components/slider.md

Does that page require any additional work for this issue?

**Comment by hyyan** [comment]
The document is for an initial, bare-bones, and incomplete implementation. A complete rewrite will be necessary to update outdated information and cover all features.

**Comment by bbrennanbasis** [comment]
@hyyan , please provide a list of what features you want documented.
