### ISSUE TITLE
Document Columns Layout

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#182]
PR: https://github.com/webforj/webforj/pull/653

# Columns Layout

1. **What is a Columns Layout?**  
   - Explanation with a basic example.

2. **Configuring Columns**  
   - By default, two columns are used.  
   - Provide a sample configuration for three columns.

3. **Breakpoints**  
   - Explain that the columns layout is responsive and respects provided breakpoints.  
   - Show how to configure columns with a sample for three columns.

4. **Column Spans and Spans per Breakpoint**  
   - Describe how to manage column spans and adjust spans according to different breakpoints.

5. **Placing Items in Specific Columns**  
   - Explain how to place items in specific columns and adjust their placement per breakpoint.  
   - Demonstrate changing the number of columns based on the container size.

7. **Items Vertical and Horizontal Alignments**

8. **Items spacing**

6. **Building a Form Sample**  
   - Rewrite the [flex form](https://documentation.webforj.com/docs/components/flex_layouts#example-form) example using the columns layout.

**Comment by bbrennanbasis** [comment]
The pull request https://github.com/webforj/webforj-docs/pull/233 closes this issue.
