### ISSUE TITLE
Broken Field URL Demos

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#330]
All field URL demos are currently broken. This issue is linked to [webforj-docs-samples pull request #101](https://github.com/webforj/webforj-docs-samples/pull/101).

**Comment by laurenic0l** [comment]
Looking into this... the demos seem to be working fine locally. I'm not sure why the URLs aren't working.

**Comment by bbrennanbasis** [comment]
The US server has been updated and the URLs for the field samples are no longer broken.
