### ISSUE TITLE
Remove extra space in ChoiceBox > Constructors > `ChoiceBox(String label, ComponentEventListener< ListSelectEvent> selectListener)`

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#54]
Before :

`ChoiceBox(String label, ComponentEventListener< ListSelectEvent> selectListener)`

After: 

`ChoiceBox(String label, ComponentEventListener<ListSelectEvent> selectListener)`

**Comment by gosteenBASIS** [comment]
Closing this issue, since it is overridden by Issue 158: Remove all constructors sections from all components docs 
https://github.com/webforj/webforj-docs/issues/158
