### ISSUE TITLE
Firefox shows hidden menu items

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#62]
![Screenshot 2023-12-04 at 12 01 10 PM](https://github.com/DwcJava/dwcjava.github.io/assets/4313420/1b49b5e9-96b0-4cc6-a98d-1d34b6c0b7cd)

**Comment by MatthewHawkins** [comment]
Fixed this issue 
![image](https://github.com/webforj/webforj-docs/assets/56275404/85eafc9c-f0ba-4809-bd45-465282681ec4)
